name: CreativeNbtControl
main: net.craftersland.creativeNBT.CC
version: 1.17
author: CraftersLand
website: www.craftersland.net
load: STARTUP
description: Control over creative NBT data copy function.
api-version: 1.17
commands:
  cnc:
    description: The main command.
permissions:
  CNC.admin:
    description: Admin commands access
    default: op
  CNC.bypass:
    description: Unlock access to creative NBT copy feature.
    default: op
  CNC.bypass.enchants:
    description: Unlock access to copy enchants.
    default: op
